CREATE TABLE `t_order` (
  `ID_` int(20) NOT NULL AUTO_INCREMENT,
  `CLIENTNAME_` varchar(200) DEFAULT NULL,
  `AMOUNT_` decimal(22,2) DEFAULT NULL,
  `CREATETIME` timestamp DEFAULT '0000-00-00 00:00:00',
  `IS_DELETE_` int(1) DEFAULT '0' COMMENT '删除标识(1:已删除;0:正常)',
  `IS_FINAL_` int(1) DEFAULT '0' COMMENT '删除不可修改',
  `CRT_TIME_` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '数据创建时间',
  `UPD_TIME_` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '数据最后修改时间',
  `CRT_USER_ID_` int(10) DEFAULT NULL COMMENT '数据创建用户编号',
  `UPD_USER_ID_` int(10) DEFAULT NULL COMMENT '数据修改用户编号',
  PRIMARY KEY (`ID_`)
);

CREATE TABLE `t_user` (
  `ID_` int(20) NOT NULL AUTO_INCREMENT,
  `USERNAME_` varchar(200) DEFAULT NULL,
  `SEX_` int(1) DEFAULT NULL,
  `CREATETIME_` timestamp DEFAULT '0000-00-00 00:00:00',
  `IS_DELETE_` int(1) DEFAULT '0' COMMENT '删除标识(1:已删除;0:正常)',
  `IS_FINAL_` int(1) DEFAULT '0' COMMENT '删除不可修改',
  `CRT_TIME_` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '数据创建时间',
  `UPD_TIME_` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '数据最后修改时间',
  `CRT_USER_ID_` int(10) DEFAULT NULL COMMENT '数据创建用户编号',
  `UPD_USER_ID_` int(10) DEFAULT NULL COMMENT '数据修改用户编号',
  PRIMARY KEY (`ID_`)
) ;

CREATE TABLE `t_dept` (
  `ID_` bigint(20) NOT NULL AUTO_INCREMENT,
  `DEPT_NAME_` varchar(200) DEFAULT NULL,
  `DEPT_CODE_` varchar(200) DEFAULT NULL,
  `REMARK_` varchar(200) DEFAULT NULL,
  `IS_DELETE_` int(1) DEFAULT '0' COMMENT '删除标识(1:已删除;0:正常)',
  `IS_FINAL_` int(1) DEFAULT '0' COMMENT '删除不可修改',
  `CRT_TIME_` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '数据创建时间',
  `UPD_TIME_` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '数据最后修改时间',
  `CRT_USER_ID_` int(10) DEFAULT NULL COMMENT '数据创建用户编号',
  `UPD_USER_ID_` int(10) DEFAULT NULL COMMENT '数据修改用户编号',
  PRIMARY KEY (`ID_`)
) 

CREATE TABLE `FE_STUDENT` (
  `STUDENT_ID_` bigint(20) NOT NULL AUTO_INCREMENT,
  `STUDENT_NAME_` varchar(200) DEFAULT NULL,
  `SEX_` tinyint DEFAULT NULL,
  `REMARK_` varchar(200) DEFAULT NULL,
  `IS_DELETE_` int(1) DEFAULT '0' COMMENT '删除标识(1:已删除;0:正常)',
  `IS_FINAL_` int(1) DEFAULT '0' COMMENT '删除不可修改',
  `CRT_TIME_` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据创建时间',
  `UPD_TIME_` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间',
  `CRT_USER_ID_` int(10) DEFAULT NULL COMMENT '数据创建用户编号',
  `UPD_USER_ID_` int(10) DEFAULT NULL COMMENT '数据修改用户编号',
  PRIMARY KEY (`STUDENT_ID_`)
);


CREATE TABLE `FE_GROUP` (
  `GROUP_ID_` bigint(20) NOT NULL AUTO_INCREMENT,
  `GROUP_NAME_` varchar(200) DEFAULT NULL,
  `IS_DELETE_` int(1) DEFAULT '0' COMMENT '删除标识(1:已删除;0:正常)',
  `IS_FINAL_` int(1) DEFAULT '0' COMMENT '删除不可修改',
  `CRT_TIME_` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据创建时间',
  `UPD_TIME_` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间',
  `CRT_USER_ID_` int(10) DEFAULT NULL COMMENT '数据创建用户编号',
  `UPD_USER_ID_` int(10) DEFAULT NULL COMMENT '数据修改用户编号',
  PRIMARY KEY (`GROUP_ID_`)
);

CREATE TABLE `FE_GROUP_STUDENT` (
  `JOIN_ID_` bigint(20) NOT NULL AUTO_INCREMENT,
  `STUDENT_ID_` bigint(20) DEFAULT NULL,
  `GROUP_ID_` bigint(20) DEFAULT NULL,
  `CRT_TIME_` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '数据创建时间',
  `CRT_USER_ID_` int(10) DEFAULT NULL COMMENT '数据创建用户编号',
  PRIMARY KEY (`JOIN_ID_`)
);

